server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 设置useSSL=true并为服务器证书验证提供信任存储
    url: jdbc:mysql://127.0.0.1:3306/peakfortake?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456

#mybatis:
#  configuration:
#    # 在properties中添加以下配置，在执行查询后，可以将数据库的NN_NN格式字段，在java结果集对象中自动转换成驼峰命名参数
#    map-underscore-to-camel-case: true

logging:
  level:
    # 打印sql日志到控制台
    com.huibo.demo.mapper.*: debug